package com.dev1lroot.mcmods.omnitech;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import net.neoforged.fml.ModList;
import net.neoforged.fml.jarcontents.JarContents;

/**
 * Reads every {@code data/omnitech/armor_material/<name>.json} from the mod JAR
 * at startup and calls {@link ArmorSet#create} for each one, replacing the
 * hard-coded entries that were previously in {@code OmniTechArmors}.
 *
 * <p>JSON schema (generated by recipe_generator.py):
 * <pre>{@code
 * {
 *   "durability_multiplier": 20,
 *   "defense_boots":          2,
 *   "defense_leggings":       5,
 *   "defense_chestplate":     7,
 *   "defense_helmet":         3,
 *   "defense_body":           6,
 *   "enchantability":        14,
 *   "toughness":             0.0,
 *   "knockback_resistance":  0.0,
 *   "repair_ingredient":     "omnitech:steel_ingot"
 * }
 * }</pre>
 */
public class ArmorSetLoader {

    private static final Gson GSON = new Gson();
    static final String ARMOR_MATERIAL_PATH = "data/omnitech/armor_material";

    public static void loadAll() {
        JarContents contents = ModList.get()
                .getModFileById(OmniTech.MODID)
                .getFile()
                .getContents();

        int[] count = {0};

        contents.visitContent(ARMOR_MATERIAL_PATH, (relativePath, resource) -> {
            if (!relativePath.endsWith(".json")) return;
            String remainder = relativePath.substring(ARMOR_MATERIAL_PATH.length() + 1);
            if (remainder.contains("/")) return;

            String name = remainder.substring(0, remainder.length() - 5);

            try (var reader = resource.bufferedReader()) {
                JsonObject json = GSON.fromJson(reader, JsonObject.class);

                int    durMult = json.has("durability_multiplier")  ? json.get("durability_multiplier").getAsInt()  : 15;
                int    dBoots  = json.has("defense_boots")          ? json.get("defense_boots").getAsInt()          : 2;
                int    dLegs   = json.has("defense_leggings")       ? json.get("defense_leggings").getAsInt()       : 5;
                int    dChest  = json.has("defense_chestplate")     ? json.get("defense_chestplate").getAsInt()     : 6;
                int    dHelm   = json.has("defense_helmet")         ? json.get("defense_helmet").getAsInt()         : 2;
                int    dBody   = json.has("defense_body")           ? json.get("defense_body").getAsInt()           : 5;
                int    ench    = json.has("enchantability")         ? json.get("enchantability").getAsInt()         : 10;
                float  tough   = json.has("toughness")              ? json.get("toughness").getAsFloat()            : 0.0f;
                float  kbRes   = json.has("knockback_resistance")   ? json.get("knockback_resistance").getAsFloat() : 0.0f;
                String repair  = json.has("repair_ingredient")      ? json.get("repair_ingredient").getAsString()   : "omnitech:" + name + "_ingot";

                int[] defense = {dBoots, dLegs, dChest, dHelm, dBody};

                ArmorSet.create(name, OmniTechItems.REGISTRY, durMult, defense, ench, tough, kbRes, repair);
                count[0]++;
                OmniTech.LOGGER.debug("[ArmorSetLoader] Registered armor set: {}", name);

            } catch (Exception e) {
                OmniTech.LOGGER.error("[ArmorSetLoader] Failed to parse '{}': {}", name, e.getMessage());
            }
        });

        OmniTech.LOGGER.info("[ArmorSetLoader] {} armor sets registered from JSON", count[0]);
    }
}
