/*
 * Copyright (c) 2026 David Eichendorf <admin@dev1lroot.com>
 * SPDX-License-Identifier: GPL-3.0-only
 */
package com.dev1lroot.mcmods.omnitech;

import com.dev1lroot.mcmods.omnitech.items.BatteryItem;
import com.dev1lroot.mcmods.omnitech.items.BoreHeadItem;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import net.minecraft.resources.Identifier;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.block.Block;
import net.neoforged.fml.ModList;
import net.neoforged.fml.jarcontents.JarContents;
import net.neoforged.neoforge.registries.DeferredItem;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.function.BiConsumer;

/**
 * Registers the Bore's swappable parts from the mod JAR (both generated by
 * {@code tools/bore_factory.py}):
 *
 * <pre>{@code
 * data/omnitech/bore_head/<material>.json  ->  omnitech:<material>_bore_head
 * {
 *   "tier": "iron",              // wood | stone | iron | diamond | netherite
 *   "hardness": 608,             // Vickers, MPa (tooltip + sort order)
 *   "speed": 7.7,
 *   "durability": 850,           // blocks
 *   "energy_per_block": 4,       // kJ
 *   "enchantability": 14,
 *   "formula": "Fe",
 *   "repair_ingredient": "minecraft:iron_ingot",   // via tag omnitech:repairs/<item>
 *   "fire_resistant": false
 * }
 *
 * data/omnitech/battery/<id>.json  ->  omnitech:<id>_battery
 * { "name": "Lead-Acid", "anode": "Pb", "cathode": "PbO₂", "cell_voltage": 2.0, "capacity_kj": 3500 }
 * }</pre>
 *
 * Must run before {@link OmniTechItems#REGISTRY} is registered on the mod bus.
 */
public class BoreLoader {

    private static final Gson GSON = new Gson();

    /** Heads, soft → hard; batteries by capacity — the creative-tab order. */
    public static final List<DeferredItem<BoreHeadItem>> HEADS = new ArrayList<>();
    public static final List<DeferredItem<BatteryItem>> BATTERIES = new ArrayList<>();

    public static void loadAll() {
        record Head(String name, JsonObject json) {}
        record Battery(String name, JsonObject json) {}
        List<Head> heads = new ArrayList<>();
        List<Battery> batteries = new ArrayList<>();
        visit("data/omnitech/bore_head", (name, json) -> heads.add(new Head(name, json)));
        visit("data/omnitech/battery", (name, json) -> batteries.add(new Battery(name, json)));

        heads.sort(Comparator.comparingInt(h -> h.json().get("hardness").getAsInt()));
        batteries.sort(Comparator.comparingInt(b -> b.json().get("capacity_kj").getAsInt()));

        for (Head h : heads) {
            JsonObject j = h.json();
            String item = h.name() + "_bore_head";
            String tier = str(j, "tier", "iron");
            TagKey<Block> incorrect = incorrectFor(tier);
            float speed = j.get("speed").getAsFloat();
            int energy = j.get("energy_per_block").getAsInt();
            int hardness = j.get("hardness").getAsInt();
            int durability = j.get("durability").getAsInt();
            int ench = j.has("enchantability") ? j.get("enchantability").getAsInt() : 10;
            boolean fireRes = j.has("fire_resistant") && j.get("fire_resistant").getAsBoolean();
            String formula = str(j, "formula", "");

            HEADS.add(OmniTechItems.REGISTRY.registerItem(item, props -> {
                props = props.durability(durability).enchantable(ench)
                        .repairable(ItemTags.create(Identifier.fromNamespaceAndPath(OmniTech.MODID, "repairs/" + item)));
                if (fireRes) props = props.fireResistant();
                if (!formula.isEmpty()) props = props.component(OmniTechDataComponents.FORMULA.get(), formula);
                return new BoreHeadItem(tier, incorrect, speed, energy, hardness, props);
            }));
        }

        for (Battery b : batteries) {
            JsonObject j = b.json();
            String chemistry = str(j, "name", b.name());
            String anode = str(j, "anode", "?");
            String cathode = str(j, "cathode", "?");
            float cellV = j.get("cell_voltage").getAsFloat();
            int capacity = j.get("capacity_kj").getAsInt();
            BATTERIES.add(OmniTechItems.REGISTRY.registerItem(b.name() + "_battery",
                    props -> new BatteryItem(chemistry, anode, cathode, cellV, capacity, props)));
        }

        OmniTech.LOGGER.info("[BoreLoader] {} bore heads, {} batteries registered from JSON",
                HEADS.size(), BATTERIES.size());
    }

    /** A fully charged copy of a battery, for the creative tab. */
    public static net.minecraft.world.item.ItemStack charged(BatteryItem battery) {
        var stack = new net.minecraft.world.item.ItemStack(battery);
        battery.setEnergy(stack, battery.capacityKj);
        return stack;
    }

    /** Creative-tab bore: the hardest head and the biggest battery, fully charged. */
    public static net.minecraft.world.item.ItemStack assembledBore() {
        var bore = new net.minecraft.world.item.ItemStack(OmniTechItems.BORE.get());
        if (!HEADS.isEmpty() && !BATTERIES.isEmpty()) {
            com.dev1lroot.mcmods.omnitech.items.BoreItem.setParts(bore,
                    new net.minecraft.world.item.ItemStack(HEADS.getLast().get()),
                    charged(BATTERIES.getLast().get()));
        }
        return bore;
    }

    private static void visit(String root, BiConsumer<String, JsonObject> out) {
        JarContents contents = ModList.get().getModFileById(OmniTech.MODID).getFile().getContents();
        contents.visitContent(root, (relativePath, resource) -> {
            if (!relativePath.endsWith(".json")) return;
            String remainder = relativePath.substring(root.length() + 1);
            if (remainder.contains("/")) return;
            String name = remainder.substring(0, remainder.length() - 5);
            try (var reader = resource.bufferedReader()) {
                out.accept(name, GSON.fromJson(reader, JsonObject.class));
            } catch (Exception e) {
                OmniTech.LOGGER.error("[BoreLoader] Failed to parse '{}/{}': {}", root, name, e.getMessage());
            }
        });
    }

    private static String str(JsonObject j, String key, String def) {
        return j.has(key) ? j.get(key).getAsString() : def;
    }

    private static TagKey<Block> incorrectFor(String tier) {
        return switch (tier) {
            case "wood"      -> BlockTags.INCORRECT_FOR_WOODEN_TOOL;
            case "stone"     -> BlockTags.INCORRECT_FOR_STONE_TOOL;
            case "diamond"   -> BlockTags.INCORRECT_FOR_DIAMOND_TOOL;
            case "netherite" -> BlockTags.INCORRECT_FOR_NETHERITE_TOOL;
            default          -> BlockTags.INCORRECT_FOR_IRON_TOOL;
        };
    }
}
