package com.dev1lroot.mcmods.omnitech;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import net.minecraft.resources.Identifier;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.block.Block;
import net.neoforged.fml.ModList;
import net.neoforged.fml.jarcontents.JarContents;

/**
 * Reads every {@code data/omnitech/tool_material/<name>.json} from the mod JAR
 * at startup and calls {@link ToolSet#create} for each one, replacing the
 * hard-coded entries that were previously in {@code OmniTechTools}.
 *
 * <p>JSON schema (generated by recipe_generator.py):
 * <pre>{@code
 * {
 *   "incorrect_for_drops_tag": "minecraft:incorrect_for_iron_tool",
 *   "durability":              800,
 *   "speed":                   7.5,
 *   "attack_damage_bonus":     2.5,
 *   "enchantability":          14,
 *   "repair_ingredient":       "omnitech:steel_ingot"
 * }
 * }</pre>
 */
public class ToolSetLoader {

    private static final Gson GSON = new Gson();
    static final String TOOL_MATERIAL_PATH = "data/omnitech/tool_material";

    public static void loadAll() {
        JarContents contents = ModList.get()
                .getModFileById(OmniTech.MODID)
                .getFile()
                .getContents();

        int[] count = {0};

        contents.visitContent(TOOL_MATERIAL_PATH, (relativePath, resource) -> {
            if (!relativePath.endsWith(".json")) return;
            String remainder = relativePath.substring(TOOL_MATERIAL_PATH.length() + 1);
            if (remainder.contains("/")) return;

            String name = remainder.substring(0, remainder.length() - 5);

            try (var reader = resource.bufferedReader()) {
                JsonObject json = GSON.fromJson(reader, JsonObject.class);

                String tagId    = json.has("incorrect_for_drops_tag")
                        ? json.get("incorrect_for_drops_tag").getAsString()
                        : "minecraft:incorrect_for_iron_tool";
                int    dur      = json.has("durability")         ? json.get("durability").getAsInt()          : 250;
                float  speed    = json.has("speed")              ? json.get("speed").getAsFloat()             : 6.0f;
                float  atk      = json.has("attack_damage_bonus")? json.get("attack_damage_bonus").getAsFloat(): 2.0f;
                int    ench     = json.has("enchantability")     ? json.get("enchantability").getAsInt()      : 14;
                String repair   = json.has("repair_ingredient")  ? json.get("repair_ingredient").getAsString(): "omnitech:" + name + "_ingot";

                TagKey<Block> dropTag = blockTag(tagId);

                ToolSet.create(name, OmniTechItems.REGISTRY, dropTag, dur, speed, atk, ench, repair);
                count[0]++;
                OmniTech.LOGGER.debug("[ToolSetLoader] Registered tool set: {}", name);

            } catch (Exception e) {
                OmniTech.LOGGER.error("[ToolSetLoader] Failed to parse '{}': {}", name, e.getMessage());
            }
        });

        OmniTech.LOGGER.info("[ToolSetLoader] {} tool sets registered from JSON", count[0]);
    }

    private static TagKey<Block> blockTag(String id) {
        return switch (id) {
            case "minecraft:incorrect_for_stone_tool"   -> BlockTags.INCORRECT_FOR_STONE_TOOL;
            case "minecraft:incorrect_for_diamond_tool" -> BlockTags.INCORRECT_FOR_DIAMOND_TOOL;
            case "minecraft:incorrect_for_netherite_tool" -> BlockTags.INCORRECT_FOR_NETHERITE_TOOL;
            default -> BlockTags.INCORRECT_FOR_IRON_TOOL;
        };
    }
}
